### ISSUE TITLE
Add translate feature

### ISSUE THREAD

**Issue by grokify** [tylerlong/glip-plus-dist#2]
[WeChat 5.3 for iOS](http://www.wechat.com/en/iPhone_5_3.html) has a great translate feature that would be nice to add to Glip. Is there any possibility to add something like this to Glip Plus?

When I use this in iOS, it says the translation was done by Microsoft Translator.

Here are the screen shots from their announcement.

![wechat_7](https://cloud.githubusercontent.com/assets/209872/17597819/6f2074ee-5fac-11e6-8587-59bf5792a098.jpg) ![wechat_8](https://cloud.githubusercontent.com/assets/209872/17597821/72200452-5fac-11e6-939b-bdc38193497f.jpg)

**Comment by tylerlong** [comment]
I think it is quite possible if we could find stable and free translation service. 

I like this idea. If you have any suggestions about the implementation, please leave comments.

**Comment by tylerlong** [comment]
A simple solution is to show a popup window displaying the following url:

https://translate.google.com/#auto/en/%E4%BD%A0%E5%A5%BD%EF%BC%8C%E4%B8%96%E7%95%8C

Pros: 
- No API needed.
- It's free.

**Comment by tylerlong** [comment]
Done. Please upgrade to version 0.6.0

![untitled](https://cloud.githubusercontent.com/assets/733544/17629511/55da268c-60ed-11e6-84c4-f3716c802bec.gif)

Maybe it's not the ideal way but we can always improve it later.

**Comment by u9520107** [comment]
cool! We can try a few translating services perhaps. You still need to vpn out to use Google translate in China right?

**Comment by tylerlong** [comment]
@u9520107 yes exactly.  We can do more investigation. It's not easy to find a good, stable and free translation service.

**Comment by zengfenfei** [comment]
@tylerlong Why not consider chargeable service?

**Comment by tylerlong** [comment]
@zengfenfei We are not going to charge users and we are not going to pay for the service ourselves either.

**Comment by tylerlong** [comment]
Close it for now. Feel free to add comments.
